channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.6.2
  - alembic=1.4.2
  - antlr-python-runtime=4.7.2
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.4
  - blinker=1.4
  - bokeh=2.0.1
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cartopy=0.17.0
  - certifi=2020.4.5.1
  - certipy=0.1.3
  - cf-units=2.1.4
  - cffi=1.14.0
  - cftime=1.1.1.2
  - chardet=3.0.4
  - click=7.1.1
  - cloudpickle=1.3.0
  - configurable-http-proxy=4.2.1
  - cryptography=2.8
  - curl=7.68.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.14.0
  - dask-core=2.14.0
  - dask_labextension=0.3.3
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.14.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.1
  - fsspec=0.7.1
  - geos=3.7.2
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - hdf4=4.2.13
  - hdf5=1.10.5
  - heapdict=1.0.1
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - iris=2.4.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9c
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter-server-proxy=1.1.0
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - jupyter_telemetry=0.0.5
  - jupyterhub=1.1.0
  - jupyterhub-base=1.1.0
  - jupyterlab=1.2.7
  - jupyterlab_server=1.1.0
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.34.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - llvm-openmp=9.0.1
  - locket=0.2.0
  - lz4-c=1.8.3
  - mako=1.1.0
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - msgpack-python=1.0.0
  - multidict=4.7.5
  - nbconvert=5.4.1
  - nbformat=5.0.4
  - ncurses=6.1
  - netcdf4=1.5.3
  - nodejs=13.12.0
  - notebook=5.7.8
  - nss=3.47
  - nteract_on_jupyter=2.1.3
  - numpy=1.18.1
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1f
  - owslib=0.19.2
  - packaging=20.1
  - pamela=1.0.0
  - pandas=1.0.3
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - partd=1.1.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.1
  - pip=20.0.2
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - psutil=5.7.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pycurl=7.43.0.5
  - pyepsg=0.4.0
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pykdtree=1.3.1
  - pyke=1.1.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=1.9.6
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python-json-logger=0.1.11
  - python_abi=3.7
  - pytz=2019.3
  - pyyaml=5.3.1
  - pyzmq=19.0.0
  - qt=5.12.5
  - readline=8.0
  - requests=2.23.0
  - ruamel.yaml=0.16.6
  - ruamel.yaml.clib=0.2.0
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - shapely=1.6.4
  - simpervisor=0.3
  - six=1.14.0
  - sortedcontainers=2.1.0
  - sqlalchemy=1.3.15
  - sqlite=3.30.1
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - udunits2=2.2.27.6
  - urllib3=1.25.7
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.4.2
  - xarray=0.15.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.2
  - yarl=1.3.0
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - azure-storage-blob=2.1.0
  - h5netcdf=2.10.0
  - pip:
      - pyqt5-sip==4.19.18
      - pyqtwebengine==5.12.1
